### ISSUE TITLE
Error when trying to setup

### ISSUE THREAD

**Issue by TheSalesOpsGuy** [alex-page/add-new-issue-project#3]
👋 @alex-page thanks for creating this! I'm getting an error though when I try to add it to a repo, any thoughts/help debugging?
```
### STARTED alex-page/add-new-issue-project 23:08:09Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
169185f82c45: Pulling fs layer
0ccde4b6b241: Pulling fs layer
d0372f57daa2: Pulling fs layer
165911d108d6: Pulling fs layer
54996bce1de5: Pulling fs layer
165911d108d6: Waiting
54996bce1de5: Waiting
d0372f57daa2: Verifying Checksum
d0372f57daa2: Download complete
0ccde4b6b241: Verifying Checksum
0ccde4b6b241: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
165911d108d6: Verifying Checksum
165911d108d6: Download complete
54996bce1de5: Verifying Checksum
54996bce1de5: Download complete
169185f82c45: Pull complete
0ccde4b6b241: Pull complete
d0372f57daa2: Pull complete
165911d108d6: Pull complete
54996bce1de5: Pull complete
Digest: sha256:c9bb432ec5ec08ee08b040a9fccacebbbf8a91444dac4721600cf5dca9dae57e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9: Pulling from gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1
bdf0201b3a05: Already exists
26f0dbb4f100: Already exists
9af56c7c17da: Already exists
0428db131795: Pulling fs layer
6763f185c09a: Pulling fs layer
6965038be95a: Pulling fs layer
0428db131795: Verifying Checksum
0428db131795: Download complete
6965038be95a: Verifying Checksum
6965038be95a: Download complete
6763f185c09a: Verifying Checksum
6763f185c09a: Download complete
0428db131795: Pull complete
6763f185c09a: Pull complete
6965038be95a: Pull complete
Digest: sha256:bffd9b38f4bfd766f2854cd4822ac782b5c77ed57a34ea43fb4b64319974df74
Status: Downloaded newer image for gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Step 1/9 : FROM node:alpine
alpine: Pulling from library/node
Digest: sha256:73ffbb3a57e8934ae45165fcb1d80f639ef2eb2cbd6821ab4af4a61b53b8241e
Status: Downloaded newer image for node:alpine
 ---> 1bdfa12c22dc
Step 2/9 : LABEL "com.github.actions.name"="Add new issues to project"
 ---> Using cache
 ---> a8b4a7e45513
Step 3/9 : LABEL "com.github.actions.description"="✨ Magically add new issues to projects"
 ---> Using cache
 ---> 8f558c1d06f2
Step 4/9 : LABEL "com.github.actions.icon"="plus"
 ---> Using cache
 ---> 4c29880dec3e
Step 5/9 : LABEL "com.github.actions.color"="green"
 ---> Using cache
 ---> cf2f1e77b373
Step 6/9 : COPY package*.json ./
 ---> Using cache
 ---> 48a24a58a51f
Step 7/9 : RUN npm ci
 ---> Using cache
 ---> da90025cf90a
Step 8/9 : COPY . .
 ---> Using cache
 ---> 7e48b5dc2cf3
Step 9/9 : ENTRYPOINT ["node", "/index.js"]
 ---> Using cache
 ---> 20dac641a68f
Successfully built 20dac641a68f
Successfully tagged gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
✖  error     Event `issues.edited` is not supported by this action.

### DECLINED alex-page/add-new-issue-project 23:08:19Z (10.619s)```

**Comment by alex-page** [comment]
Hi @TheSalesOpsGuy this seems like a bug. It should not log an error when editing issues. 

---

I did some investigation, the actions run correctly and end in a neutral state. The logs however are printing an error. I'll see if I can fix up the logs in the next few days.

Currently the action has to be triggered by an event. The event specified is `issue`. This triggers on all of the [issue events](https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#events-supported-in-workflow-files) which is why you see this on `issue.edited`. I'll see if I can exit without the logged error.

**Comment by alex-page** [comment]
@TheSalesOpsGuy it should now end actions that are not issues being opened in a neutral state without an error log. Let me know if you have any more problems 👍

**Comment by TheSalesOpsGuy** [comment]
👋 @alex-page 

```
### STARTED alex-page/add-new-issue-project 23:02:27Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
169185f82c45: Pulling fs layer
0ccde4b6b241: Pulling fs layer
d0372f57daa2: Pulling fs layer
165911d108d6: Pulling fs layer
54996bce1de5: Pulling fs layer
165911d108d6: Waiting
54996bce1de5: Waiting
0ccde4b6b241: Verifying Checksum
0ccde4b6b241: Download complete
d0372f57daa2: Verifying Checksum
d0372f57daa2: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
54996bce1de5: Verifying Checksum
54996bce1de5: Download complete
165911d108d6: Verifying Checksum
165911d108d6: Download complete
169185f82c45: Pull complete
0ccde4b6b241: Pull complete
d0372f57daa2: Pull complete
165911d108d6: Pull complete
54996bce1de5: Pull complete
Digest: sha256:c9bb432ec5ec08ee08b040a9fccacebbbf8a91444dac4721600cf5dca9dae57e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9: Pulling from gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1
bdf0201b3a05: Already exists
26f0dbb4f100: Already exists
9af56c7c17da: Already exists
0428db131795: Pulling fs layer
6763f185c09a: Pulling fs layer
6965038be95a: Pulling fs layer
6965038be95a: Verifying Checksum
6965038be95a: Download complete
6763f185c09a: Verifying Checksum
6763f185c09a: Download complete
0428db131795: Verifying Checksum
0428db131795: Download complete
0428db131795: Pull complete
6763f185c09a: Pull complete
6965038be95a: Pull complete
Digest: sha256:bffd9b38f4bfd766f2854cd4822ac782b5c77ed57a34ea43fb4b64319974df74
Status: Downloaded newer image for gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Step 1/9 : FROM node:alpine
alpine: Pulling from library/node
Digest: sha256:73ffbb3a57e8934ae45165fcb1d80f639ef2eb2cbd6821ab4af4a61b53b8241e
Status: Downloaded newer image for node:alpine
 ---> 1bdfa12c22dc
Step 2/9 : LABEL "com.github.actions.name"="Add new issues to project"
 ---> Using cache
 ---> a8b4a7e45513
Step 3/9 : LABEL "com.github.actions.description"="✨ Magically add new issues to projects"
 ---> Using cache
 ---> 8f558c1d06f2
Step 4/9 : LABEL "com.github.actions.icon"="plus"
 ---> Using cache
 ---> 4c29880dec3e
Step 5/9 : LABEL "com.github.actions.color"="green"
 ---> Using cache
 ---> cf2f1e77b373
Step 6/9 : COPY package*.json ./
 ---> Using cache
 ---> 48a24a58a51f
Step 7/9 : RUN npm ci
 ---> Using cache
 ---> da90025cf90a
Step 8/9 : COPY . .
 ---> Using cache
 ---> 7e48b5dc2cf3
Step 9/9 : ENTRYPOINT ["node", "/index.js"]
 ---> Using cache
 ---> 20dac641a68f
Successfully built 20dac641a68f
Successfully tagged gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
✖  fatal     GraphqlError: Resource not accessible by integration 
    at request.then.response (/node_modules/@octokit/graphql/lib/graphql.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

### FAILED alex-page/add-new-issue-project 23:02:38Z (10.64s)
```

It seems like its still erroring for me when I create a new issue

**Comment by alex-page** [comment]
@TheSalesOpsGuy Ok this is a different error. I will open a new issue!
